# Change baseurl before deploy
baseurl = "https://iamjeremie.me"
languageCode = "en-us"
paginate = 8
title = "Jérémie Litzler"
description = "I share my notes and experiences that can be useful to one of you. Enjoy the read!"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
# disqusShortname = "hugo-theme-stack"

# See https://gohugo.io/getting-started/configuration/#removepathaccents
removePathAccents = true

[params]
custom_css = ["css/custom-style.css"]
